version: "3.7"

services:
    jenkins:
        image: jenkins
        #environment:
        #  JAVA_OPTS : "
        #    -Djava.util.logging.config.file=/var/jenkins_home/log.properties
        #    "
        ports:
          - 8042:8080
          - 50000:50000
        volumes:
          - data:/var/local/jenkins_home
          - /var/run/docker.sock:/var/run/docker.sock
        networks:
          - jenkins
        deploy:
            resources:
                limits:
                    memory: 512M
                    cpus: '1.5'
volumes:
  data:
networks:
  jenkins:
    driver: overlay
  
            
