version: "3.7"

services:
    jenkins:
        image: jenkins/jenkins
        environment:
          JAVA_OPTS : "
            -Djava.util.logging.config.file=/var/jenkins_home/log.properties
            "
        ports:
          - 8042:8080
          - 50000:50000
        volumes:
          - data:/var/jenkins_home
        networks:
          - jenkins
        deploy:
            resources:
                limits:
                    memory: 512M
                    cpus: '0.5'
volumes:
  data:
networks:
  jenkins:
    driver: overlay
  
            
